# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Coordinates-VandH
version:      1.11
version_from: VandH.pm
installdirs:  site
requires:
    Math::Trig:                    Math::Complex

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
